
[font]
size = 20.0

[font.normal]
family = "Hack Nerd Font Propo"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Propo"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Propo"
style = "Italic"

[window]
# opacity = 0.95

[bell]
command = "None"

[terminal.shell]
program = "wsl"
args = ["-d", "archlinux", "--cd", "~"]

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.50"

[colors.primary]
background = "0x161718"
foreground = "0xc4c8c5"

[colors.cursor]
text = "0x161718"
cursor = "0x4da3ff"

[colors.selection]
text = "0x161718"
background = "0x444444"

[colors.normal]
black   = "0x000000"
red     = "0xfc5ef0"
green   = "0x86c38a"
yellow  = "0xffd6b1"
blue    = "0x85befd"
magenta = "0xb9b5fc"
cyan    = "0x85befd"
white   = "0xdfdfdf"

[colors.bright]
black   = "0x000000"
red     = "0xfc5ef0"
green   = "0x94f936"
yellow  = "0xf5ffa7"
blue    = "0x95cbfe"
magenta = "0xb9b5fc"
cyan    = "0x85befd"
white   = "0xdfdfdf"
